// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SendMessages.Persistence
{
    public partial class EsoChat
    {
        public DateTime TimeStamp { get; set; }
        public string EsoUserId { get; set; }
        public string Text { get; set; }
        public string Channel { get; set; }
    }
}